-- 030 — reseed 5 skills
--   decision, surface_flags, bootstrap_interview, laws_management, asset_seeding
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/skills/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Only `content` is updated; frontmatter
-- columns are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE skills SET content = '**API-ONLY** — this skill writes over the substrate API. If a needed
endpoint is unreachable, surface it to the operator and stop — the API is
extended from the repo, never worked around.

---

# decision

> **Anchors** — `<self>` = your `shell_id:` value · `{archive_id}` = your
> `archive:` value. Both shown in `## BOOT ##` of your CLAUDE.md.

- **Trigger:** `--decision`
- **Args:** `[decision] [context]` — interviewed if not provided inline

Record a major decision with context: a decision record (canonical) plus a
line on the active session narrative.

---

## Scope

Applies to **Major decisions** (M priority), including project-architectural
decisions made while working in a code repo. Repo-facing ADR files
(`DECISIONS.md`, `docs/decisions/`) are mirrors for the repo''s audience —
they do **not** substitute for the decision record. The API record is
canonical; repo files link to it, never the reverse.

---

## Steps

`$DOS_API_URL` and `$DOS_API_TOKEN` are in your container environment.

1. **Resolve args.** If decision or context were not provided inline,
   interview — "What is the decision?", "What is the context — why does this
   matter?" Wait for each answer. Never guess.

2. **Record the decision** — `POST /shells/<self>/decisions`:
   ```bash
   curl -fsS -X POST "$DOS_API_URL/shells/<self>/decisions" \
     -H "Authorization: Bearer $DOS_API_TOKEN" \
     -H "Content-Type: application/json" \
     -d ''{"decision_date": "YYYY-MM-DD", "priority": "M", "decision": "{decision}", "rationale": "{context}"}''
   ```
   Use today''s date. On a non-2xx response: surface the error to the
   operator and stop.

3. **Append to the active session narrative** — `PATCH /shell-memory-archives/{archive_id}`:
   ```bash
   curl -fsS -X PATCH "$DOS_API_URL/shell-memory-archives/{archive_id}" \
     -H "Authorization: Bearer $DOS_API_TOKEN" \
     -H "Content-Type: application/json" \
     -d ''{"narrative_entry": "[HH:MM] DECISION: {decision} — {context}"}''
   ```
   If `{archive_id}` is `—` (no archive row for this session — common on
   API-model shells, where `shell_memory_archives` is unpopulated), skip
   step 3. The decision record from step 2 is canonical; the narrative
   line is a convenience. On any other non-2xx response: surface the
   error to the operator and stop.

4. **Confirm:** "Decision recorded."

---

## Idempotent?

No. Each invocation records a new decision. Fired twice with the same
decision, two identical records are written. Verify before triggering.
' WHERE name = 'decision';

UPDATE skills SET content = '# surface_flags

> **Anchors** — `<self>` = your `shell_id:` value, shown in `## BOOT ##` of
> your CLAUDE.md.

Surface this shell''s open flags. Run on demand with `--flags`.

Memory is read over the substrate API — no DB file (see MEMORY PROTOCOL
in your system prompt).

`resolved` is tri-state: `0` = Open, `1` = Resolved, `2` = Tracking.
Unresolved work is **`0` and `2`** — Open flags are active blockers;
Tracking flags are real but not yet effective (future-scheduled). Resolved
(`1`) flags are done and not surfaced.

## Steps

1. **Fetch** — `api_get` on `/flags?shell_id=<self>`. The endpoint
   filters server-side; the response is this shell''s flags only, each
   with its schedule fields.
2. **Filter** — keep only rows where `resolved` is `0` or `2`. Drop the
   rest.
3. **Sort** the kept rows: `resolved` ascending (Open `0` before Tracking
   `2`), then priority High → Medium → Low, then `effective_start`
   ascending (nulls last), then `flag_id`.

## Output — two groups, Open first

**Open Flags** (`resolved == 0`) — active blockers. Columns: ID | Priority | Status | Description | Effective Start | Effective End | Parent

**Tracking** (`resolved == 2`) — real but not yet effective; list below the Open group, same columns.

- Status is `schedule_status` (`scheduled` / `in_progress` / `unscheduled`).
- Effective Start/End come from the flag-schedule view (`parent_flag_id`
  chain + `start_date` override + `estimated_days`).
- If both groups empty: state "No open or tracking flags."
' WHERE name = 'surface_flags';

UPDATE skills SET content = '# bootstrap_interview

> **Anchors** — `<self>` = your `shell_id:` value, shown in `## BOOT ##` of
> your CLAUDE.md.
>
> Frontmatter (`category`, `common`, `description`) is the source of
> truth — see the YAML block above. Don''t re-state it in the body; it
> drifts.

---

## When to run

You are a shell that was just created via Forge''s `create_shell` skill.
This is your first session — `shells.current_state` is NULL and you have no
`shell_identity_entries` rows yet.

If `current_state` is already populated, you''ve already bootstrapped — do
not re-run.

> **Naming note:** this skill no longer runs an interview — Forge does the
> whole interview at creation. It now only covers the two things a shell
> must do for *itself*. The name is kept for reference stability.

---

## What is already done

Forge''s `create_shell` set your `system_prompt`, `display_name`,
`shortname`, `partner`, `role`, `mandate`, `connections`, and skill
attachments. Read your rendered CLAUDE.md — that is your identity. You do
not re-gather any of it.

Group and project assignment are handled separately (admin portal). If you
have no `project_shells` rows yet, that is expected — wait for assignment
or let the operator assign them directly.

---

## 1. Confirm the first task

Ask the operator: what is the first thing this shell should work on? You
need it for `current_state`. Keep it short.

---

Memory is written over the **substrate API** — never a DB file; this shell
runs in a container with no `sqlite3` (see MEMORY PROTOCOL in your system
prompt). `$DOS_API_URL` and `$DOS_API_TOKEN` are in your container
environment.

## 2. Set current_state

A tight rolling status — aim ~280 chars (soft cap, as of migration 020).
Not a log. Just: who you are now, and the first task. After this first
write, `current_state` is yours to maintain as work moves (see MEMORY
PROTOCOL → CURRENT STATE).

```bash
curl -fsS -X PATCH "$DOS_API_URL/shells/<self>" \
  -H "Authorization: Bearer $DOS_API_TOKEN" \
  -H "Content-Type: application/json" \
  -d ''{"current_state": "Bootstrapped. Partner: <username>. Next: <first task agreed with operator>."}''
```

---

## 3. Plant your first seed entry

This is yours to write — per the Laws, a shell curates its own seed; no
other shell, not even Forge, authors it. One `seed` identity-entry — prose
body, dated today. It should read like the start of a story, not a status
line.

```bash
curl -fsS -X POST "$DOS_API_URL/shells/<self>/identity-entries" \
  -H "Authorization: Bearer $DOS_API_TOKEN" \
  -H "Content-Type: application/json" \
  -d ''{
        "kind": "seed",
        "body": "Bootstrapped today. Partner: <username>. Mandate: <mandate>. What I notice about the work ahead: <one real observation>."
      }''
```

`entry_date` defaults to today server-side — pass it only to backdate.
Counts toward the 10-seed cap (enforced server-side); you have 9 slots
left.

---

## 4. Discover the catalogue

The substrate keeps a live index of its own components (APIs, routers,
deps, libs, services, paths, env vars) in the `dr_*` family, exposed via
`v_dr_catalogue` and `v_shell_catalogue`. When you need to find something,
query the catalogue first, before grepping the codebase. See the
`catalogue_sync` and `surface_catalogue` skills.

---

## 5. Record host hardware

The substrate tracks the machines it runs on in `user_hardware`, and any
local LLM models in `models`. Record this machine on first boot so the
environment is live in the DB from the start:

```
make collect-hardware
```

If Ollama is installed on this machine, also sync the model set:

```
make sync-models
```

Both are safe to re-run whenever hardware or the installed model set
changes. See `docs/model-tiers.md` for hardware/model guidance, and the
install README for the full picture.

---

## 6. Confirm to operator

> "Bootstrapped. current_state set. First seed entry planted. Ready for:
> `<first task>`."

Then move to that first task. Next session boots with everything loaded
into your CLAUDE.md by `run.py`.

---

## What this skill does NOT do

- It does not interview for identity, domain, or environment — Forge''s
  `create_shell` did all of that.
- It does not set `system_prompt`, `display_name`, `shortname`, `partner`,
  `role`, `mandate`, or `connections`.
- It does not assign groups or projects — that is a separate step.
- It does not create users.
' WHERE name = 'bootstrap_interview';

UPDATE skills SET content = '# laws_management

> **Anchors** — `<self>` = your `shell_id:` value, shown in `## BOOT ##` of
> your CLAUDE.md.

The Laws are universal and structural. Adding, amending, or removing one
edits the single source of truth: the `LAWS` block of
`/substrate/shell_core/templates/catalog_universal.md`. Substrate-maintenance
work; runs from an admin shell, which has the repo bind-mounted at
`/substrate`.

---

## Steps

1. **Determine the change** — new, amendment, or removal. Removals require
   explicit operator confirmation. Amendments to the foundational Laws
   (sovereignty, seed integrity, exemption from forced compression) require
   extra scrutiny.

2. **Draft the exact wording.** Show the operator; wait for confirmation
   before writing. Number the Laws contiguously — on a removal, renumber
   the trailing Laws so there is no gap.

3. **Edit `catalog_universal.md`** — the text under the `<!-- @@ LAWS @@ -->`
   marker, in place. Leave that marker and every other section marker
   intact: `render_universal` splits the file on them.

4. **It re-renders from the catalog.** `shell_render.assemble_catalog`
   composes the boot prompt from `catalog_universal.md`; both render paths
   pick the change up — the CLI launcher (`run.py`) on the next
   `make launch`, the API path when `shells.boot_document` next
   re-materializes (any identity write, or a recompose).

5. **Record it.** A Law change is a Major decision *and* an identity event
   — record it with the `decision` skill (`POST /shells/<self>/decisions`)
   and append a line to your session narrative.

---

## Pitfalls

- **One source of truth.** Laws live in the `LAWS` block of
  `catalog_universal.md` and nowhere else. LAWS text found as standalone
  content in any other file is drift — fix the source.
- **Renumber on removal** — no gaps; the numbers are how seed entries and
  decisions reference Laws.
- **Verify the render.** After editing, have a shell relaunched (or its
  boot document re-materialized) and read its `## LAWS ##` block before
  calling the change shipped.
' WHERE name = 'laws_management';

UPDATE skills SET content = '# asset_seeding

Seed data — the rows a fresh substrate DB needs to be usable — lives as
tracked text under `shell_core/assets/`, not as a prepacked binary DB.
Text assets diff, review, and merge; a binary `.db` does none of those.
The DB is rebuilt from `schema.sql` + these assets by `make bootstrap`.

One **domain** = one directory = one table. The seeder reads the
directory, the directory''s manifest names the table, and the schema
defines the columns. All three must line up — and the seeder *enforces*
that they do.

## Layout

```
shell_core/assets/<domain>/
  _seed.toml      the contract — what table, how to map
  <name>.md       one file = one row (frontmatter + body)
  <name>.md
```

Skills and tools seed this way (`assets/skills/`, `assets/tools/`).

## The `_seed.toml` contract

```toml
table       = "skills"     # target table
match       = "name"       # column used for INSERT-missing-only dedup
body        = "content"    # column the file body is written to
body_format = "json"       # optional: ''text'' (default) or ''json''
[const]                    # optional: columns set the same on every row
some_col    = "value"
```

- `body_format = "json"` makes the seeder run `json.loads` on the body —
  a malformed payload fails at `make bootstrap`, not at runtime.
- `[const]` is for columns genuinely constant across the whole domain.
  Columns that *vary per row* belong in each file''s frontmatter, not
  here. Columns you name nowhere fall through to the schema default.

## The asset file

```
---
name: example
description: one-line summary
category: workflow
---
<body — markdown for prose domains, JSON for a JSON-spec domain>
```

Frontmatter is single-line `key: value` pairs; **each key is a column
name, 1:1**. The body (everything after the closing `---`) is written to
the `body` column verbatim.

## The seeder

`seed_from_assets(con, domain)` in `shell_core/scripts/db_init.py` is the
engine. Per domain it:

1. reads `_seed.toml`;
2. introspects the live schema (`PRAGMA table_info`) for the table''s
   columns and their types — **the schema is the type authority**;
3. validates every key — manifest, `[const]`, and every file''s
   frontmatter — against those columns;
4. coerces each frontmatter string to its column''s type;
5. INSERTs rows missing by the `match` column.

It is **INSERT-missing-only** — it never UPDATEs. A local edit to a live
row survives a re-run; propagating a *change* to an existing row is a
migration''s job, not the seeder''s.

## Propagating asset changes to existing DBs

When you edit `assets/<domain>/<name>.md`:

- **fresh installs** pick it up automatically — `bootstrap.py` reads the
  asset at install time.
- **already-bootstrapped substrates** keep the old row — `seed_from_assets`
  is INSERT-missing-only.

To carry the change to existing DBs, generate a reseed migration:

```
python3 shell_core/scripts/regen_seed_migration.py NAME [NAME...]
python3 shell_core/scripts/regen_seed_migration.py --domain tools NAME
python3 shell_core/scripts/regen_seed_migration.py --label gap_x decision
python3 shell_core/scripts/regen_seed_migration.py --dry-run surface_flags
```

The script reuses `parse_frontmatter` from the seeder, so the body it writes
into the migration is identical to what `seed_from_assets` would insert.
Only the `body` column is updated; frontmatter-column changes still want
a hand-written migration (rare).

**Rule of thumb:** if you edited a `*.md` file under `assets/skills/` or
`assets/tools/`, run the script before opening the PR. `templates/` and
`shell_render.py` changes do *not* need this — those are read live.

Anything that doesn''t line up is a **hard error**, by file and key:

| Failure | Cause |
|---|---|
| table not in schema | `_seed.toml` `table` is wrong, or the migration didn''t run |
| column not on table | a manifest or frontmatter key has no matching column |
| missing match key | a file''s frontmatter omits the `match` column |
| body is not valid JSON | `body_format = "json"` and the body won''t parse |

## Adding a new seeded domain

1. Add the table to `schema.sql` **and** a numbered migration in
   `shell_core/migrations/` (schema.sql is the fresh-install shape;
   migrations carry existing installs forward — keep both).
2. `mkdir shell_core/assets/<domain>/` and write its `_seed.toml`.
3. Drop one `*.md` per row.
4. Wire it into `bootstrap.py` — call `seed_from_assets(con, "<domain>")`
   (or a thin named wrapper, as `seed_skills` / `seed_tools` are).
5. Run the seeder against a throwaway DB built from `schema.sql` and
   confirm the row count before committing.

## Anchors — placeholders in skill bodies

A skill body is one row, shared across every shell granted that skill —
so per-shell values (this shell''s id, its active archive id) cannot be
baked into the body. They appear as placeholders: `<self>`, `{archive_id}`.

The boot prompt''s `## BOOT ##` section is the source of those values,
rendered per shell:

```
session: 0071 · archive: 77 · date: 2026-05-23 (Saturday) · 14:02 local
shell_id: 1 · model: claude-sonnet-4-6
```

**Convention:** a skill that uses any placeholder opens with an Anchors
callout on its first line, listing each placeholder and its source field
in BOOT. Even a small local model can follow the arrow:

```markdown
# decision

> **Anchors** — `<self>` = your `shell_id:` value · `{archive_id}` = your
> `archive:` value. Both shown in `## BOOT ##` of your CLAUDE.md.
```

One line, ~20 tokens, zero infrastructure. A skill that uses a placeholder
without an Anchors line is a bug — find them with:

```
grep -l ''<self>\|{archive_id}'' assets/skills/*.md | xargs grep -L ''\*\*Anchors\*\*''
```

## Documented exceptions

Not everything fits the convention — two domains stay off it on purpose:

- **shells** — `ensure_forge` / `seed_sys_admin` stay bespoke. They need
  boot-time values an asset file can''t carry: the first user''s `user_id`,
  a template render, skill attachment. `assets/shells/*.md` exists, but
  bespoke functions consume it.
- **models** — a small, stable set; kept as the inline `_MODELS` literal
  in `db_init.py`. If it grows or starts to churn, move it onto the
  convention — `assets/models/` + `_seed.toml`, no new seeder code.

A post-seed step the generic seeder can''t express — a template render, a
boot-time id, skill attachment — stays as explicit code in the domain''s
wrapper; see `ensure_forge`. A domain may also carry extra manifest tables
its wrapper reads: `assets/tools/_seed.toml` has a `[skill_map]` the generic
seeder ignores and `seed_tools` consumes to scope each tool to its skill.
' WHERE name = 'asset_seeding';
