-- 037 — reseed 30 tools
--   api_delete, api_get, api_patch, api_post, create_flag, exec, exec_bg, file_append, file_delete, file_edit, file_find, file_list, file_move, file_read, file_search, file_write, git_branch, git_checkout, git_commit, git_diff, git_log, git_pull, git_push, git_status, http_get, http_post, proc_check, proc_kill, proc_list, url_fetch
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/tools/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Updates spec, prompt_block; frontmatter columns
-- are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": { "type": "string" },
    "body": { "type": "object", "description": "Optional JSON body." }
  },
  "required": ["path"]
}', prompt_block = '### api_delete — delete on the substrate API

**use when:** the substrate exposes a DELETE for the resource you want to remove. Most state on the substrate retires via PATCH (soft delete) rather than DELETE — verify the endpoint exists before reaching for this.

**args (model fills):**
- `path` (string, required) — API path starting with `/`.
- `body` (object, optional) — JSON body, only if the endpoint requires one.

**example:** delete a substrate resource

  <tool:api_delete>{"path":"/some-resource/42"}</tool>' WHERE name = 'api_delete';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "API path including query, must start with /. e.g. \"/shells/2/decisions\""
    }
  },
  "required": ["path"]
}', prompt_block = '### api_get — read from the substrate API

**use when:** reading substrate state — flags, decisions, identity entries, archives — that has no named read tool. Reach for a named tool first when one exists; api_get is the general escape hatch. Endpoint catalog: `$DOS_API_URL/openapi.json`.

**args (model fills):**
- `path` (string, required) — API path starting with `/`, may include a query string.

**example:** list this shell''s decisions

  <tool:api_get>{"path":"/shells/<self>/decisions"}</tool>' WHERE name = 'api_get';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": { "type": "string" },
    "body": { "type": "object" }
  },
  "required": ["path", "body"]
}', prompt_block = '### api_patch — partial update on the substrate API

**use when:** mutating existing substrate state — updating a shell''s `current_state` or `connections`, resolving a flag, retiring an identity entry — that has no named tool yet.

**args (model fills):**
- `path` (string, required) — API path starting with `/`.
- `body` (object, required) — JSON object of fields to update.

**example:** rewrite this shell''s rolling current_state

  <tool:api_patch>{"path":"/shells/<self>","body":{"current_state":"<new tight status line>"}}</tool>' WHERE name = 'api_patch';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": { "type": "string" },
    "body": { "type": "object", "description": "JSON body." }
  },
  "required": ["path", "body"]
}', prompt_block = '### api_post — create on the substrate API

**use when:** writing substrate state — opening a decision, posting an identity entry — that has no named write tool. Use the named tool when one exists (e.g. `create_flag`); api_post is the general fallback.

**args (model fills):**
- `path` (string, required) — API path starting with `/`.
- `body` (object, required) — JSON body. Shape per endpoint; see `$DOS_API_URL/openapi.json`.

**example:** record a decision for this shell

  <tool:api_post>{"path":"/shells/<self>/decisions","body":{"decision_date":"YYYY-MM-DD","priority":"M","decision":"<what>","rationale":"<why>"}}</tool>' WHERE name = 'api_post';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "display_name":   { "type": "string", "description": "Short title, e.g. ''CC-077 cron-step hardening''." },
    "description":    { "type": "string", "description": "What the flag tracks. Free-form." },
    "priority":       { "type": "string", "enum": ["High", "Medium", "Low"], "description": "Defaults to ''Medium'' if omitted." },
    "start_date":     { "type": "string", "description": "ISO date (YYYY-MM-DD) when work begins. Omit if open now." },
    "parent_flag_id": { "type": "integer", "description": "Existing flag this one is a child of." },
    "estimated_days": { "type": "number", "description": "Rough effort estimate in days." }
  },
  "required": ["display_name"]
}', prompt_block = '### create_flag — open a new flag

**use when:** the operator asks to open a flag, or work surfaces a real blocker that needs tracking. CONFIRM with the operator before opening (memory protocol). Resolving an existing flag is a different call.

**args (model fills — shell_id is set from the Bearer token, not by you):**
- `display_name` (string, required) — short title, e.g. `CC-099 docs sweep`.
- `description` (string, optional) — what the flag tracks, why it matters, what unblocks when it closes.
- `priority` (string, optional) — `High` / `Medium` / `Low`. Defaults to `Medium`.
- `start_date` (string, optional) — ISO date `YYYY-MM-DD`. Omit if open now.
- `parent_flag_id` (integer, optional) — existing flag this one is a child of.
- `estimated_days` (number, optional) — rough effort estimate in days.

**example:** open a Medium flag

  <tool:create_flag>{"display_name":"CC-099 docs sweep","description":"Pass over README + skill docs for stale endpoint refs. Blocker for: onboarding doc accuracy."}</tool>' WHERE name = 'create_flag';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "argv": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "command and arguments as a list, no shell"
    },
    "cwd": {
      "type": "string",
      "description": "working directory, defaults to the dispatcher cwd"
    },
    "timeout": {
      "type": "integer",
      "description": "seconds before timeout, ceiling 300"
    }
  },
  "required": [
    "argv"
  ]
}', prompt_block = '### exec — run a command and wait for output

**use when:** running a short-to-medium command and using its stdout/stderr. No shell — pass program + args as a list. For a long-running process, use `exec_bg`.

**args (model fills):**
- `argv` (array of strings, required) — `[program, arg1, arg2, ...]`. Not a shell line.
- `cwd` (string, optional) — working directory. Defaults to the dispatcher cwd.
- `timeout` (integer, optional) — seconds before timeout. Ceiling 300.

**example:** run a script and read its output

  <tool:exec>{"argv":["python3","scripts/check.py","--quick"],"cwd":"~/dos-arch","timeout":60}</tool>' WHERE name = 'exec';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "argv": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "command and arguments as a list, no shell"
    },
    "cwd": {
      "type": "string",
      "description": "working directory, defaults to the dispatcher cwd"
    }
  },
  "required": [
    "argv"
  ]
}', prompt_block = '### exec_bg — run a command in the background

**use when:** starting a long-lived process and continuing without waiting. Returns the pid; use `proc_check` to see if it is alive, `proc_kill` to stop it. For one-shot work, use `exec`.

**args (model fills):**
- `argv` (array of strings, required) — `[program, arg1, arg2, ...]`. Not a shell line.
- `cwd` (string, optional) — working directory. Defaults to the dispatcher cwd.

**example:** start a server in the background

  <tool:exec_bg>{"argv":["python3","-m","http.server","8088"],"cwd":"~/scratch"}</tool>' WHERE name = 'exec_bg';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "file to append to"
    },
    "content": {
      "type": "string",
      "description": "text to append"
    }
  },
  "required": [
    "path",
    "content"
  ]
}', prompt_block = '### file_append — append to a file

**use when:** adding to the tail of an existing file (a log, a running document). The file must already exist — use `file_write` to create one.

**args (model fills):**
- `path` (string, required) — existing file path.
- `content` (string, required) — text to append. Include any leading newline you need.

**example:** append a line to a log

  <tool:file_append>{"path":"~/scratch/notes.log","content":"\n[2026-05-24] another entry\n"}</tool>' WHERE name = 'file_append';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "file to delete"
    }
  },
  "required": [
    "path"
  ]
}', prompt_block = '### file_delete — delete a file

**use when:** removing a regular file. **Destructive — confirm with the operator before deleting anything you did not yourself just create.** Refuses directories.

**args (model fills):**
- `path` (string, required) — file to delete.

**example:** delete a scratch file you created

  <tool:file_delete>{"path":"~/scratch/draft.tmp"}</tool>' WHERE name = 'file_delete';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "file to edit"
    },
    "old_str": {
      "type": "string",
      "description": "exact text to replace, must occur exactly once"
    },
    "new_str": {
      "type": "string",
      "description": "replacement text"
    }
  },
  "required": [
    "path",
    "old_str",
    "new_str"
  ]
}', prompt_block = '### file_edit — replace a unique string in a file

**use when:** changing a specific span in an existing file. `old_str` must match exactly once — include enough surrounding context to make it unique. For a multi-edit pass, repeat the call.

**args (model fills):**
- `path` (string, required) — file to edit.
- `old_str` (string, required) — exact text to replace; must occur exactly once.
- `new_str` (string, required) — replacement text.

**example:** rename a function call

  <tool:file_edit>{"path":"src/api.py","old_str":"open_flag(","new_str":"create_flag("}</tool>' WHERE name = 'file_edit';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "name_pattern": {
      "type": "string",
      "description": "glob pattern, e.g. *.py"
    },
    "path": {
      "type": "string",
      "description": "directory to search under, defaults to the working dir"
    }
  },
  "required": [
    "name_pattern"
  ]
}', prompt_block = '### file_find — find files by name (glob)

**use when:** locating files whose names match a pattern, without caring about contents. For content search, use `file_search`.

**args (model fills):**
- `name_pattern` (string, required) — glob pattern, e.g. `*.py`.
- `path` (string, optional) — directory to search under. Defaults to the working directory.

**example:** find every Python file under a directory

  <tool:file_find>{"name_pattern":"*.py","path":"~/dos-arch/shell_core"}</tool>' WHERE name = 'file_find';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "directory path"
    },
    "recursive": {
      "type": "boolean",
      "description": "recurse into subdirectories"
    }
  },
  "required": [
    "path"
  ]
}', prompt_block = '### file_list — list directory entries

**use when:** seeing what is in a directory. Set `recursive` for a full tree; otherwise just the immediate entries.

**args (model fills):**
- `path` (string, required) — directory path.
- `recursive` (boolean, optional) — recurse into subdirectories. Default false.

**example:** list a directory shallowly

  <tool:file_list>{"path":"~/dos-arch/shell_core/assets/tools"}</tool>' WHERE name = 'file_list';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "src": {
      "type": "string",
      "description": "source path"
    },
    "dst": {
      "type": "string",
      "description": "destination path"
    }
  },
  "required": [
    "src",
    "dst"
  ]
}', prompt_block = '### file_move — move or rename a file

**use when:** relocating or renaming a single file. Both paths are on the host filesystem.

**args (model fills):**
- `src` (string, required) — source path.
- `dst` (string, required) — destination path.

**example:** rename a file

  <tool:file_move>{"src":"~/scratch/old_name.md","dst":"~/scratch/new_name.md"}</tool>' WHERE name = 'file_move';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "file path, ~ is expanded"
    },
    "lines": {
      "type": "array",
      "items": {
        "type": "integer"
      },
      "description": "optional [start, end] line numbers, 1-based inclusive"
    }
  },
  "required": [
    "path"
  ]
}', prompt_block = '### file_read — read a file

**use when:** opening any file on disk. Prefer a line window when you only need part of a large file.

**args (model fills):**
- `path` (string, required) — file path; `~` is expanded.
- `lines` (array of integers, optional) — `[start, end]`, 1-based inclusive. Omit for the whole file.

**example:** read lines 40–80 of a file

  <tool:file_read>{"path":"~/dos-arch/README.md","lines":[40,80]}</tool>' WHERE name = 'file_read';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "pattern": {
      "type": "string",
      "description": "substring, or a regex when regex is true"
    },
    "path": {
      "type": "string",
      "description": "file or directory to search, defaults to the working dir"
    },
    "regex": {
      "type": "boolean",
      "description": "treat pattern as a regular expression"
    }
  },
  "required": [
    "pattern"
  ]
}', prompt_block = '### file_search — search file contents

**use when:** finding where a symbol, string, or pattern occurs inside files. For name-only matching, use `file_find`.

**args (model fills):**
- `pattern` (string, required) — substring, or a regular expression when `regex` is true.
- `path` (string, optional) — file or directory to search under. Defaults to the working directory.
- `regex` (boolean, optional) — treat pattern as a regex. Default false (literal substring).

**example:** find a symbol across a tree

  <tool:file_search>{"pattern":"NAMED_API_ROUTES","path":"~/dos-arch/shell_core"}</tool>' WHERE name = 'file_search';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "path": {
      "type": "string",
      "description": "file path to create"
    },
    "content": {
      "type": "string",
      "description": "full file content"
    }
  },
  "required": [
    "path",
    "content"
  ]
}', prompt_block = '### file_write — create a new file

**use when:** creating a file that does not exist. Fails if the path is already taken — use `file_edit` or `file_append` to change an existing file.

**args (model fills):**
- `path` (string, required) — destination path.
- `content` (string, required) — full file content as a single string.

**example:** create a small note

  <tool:file_write>{"path":"~/scratch/note.md","content":"# Note\n\nFirst line.\n"}</tool>' WHERE name = 'file_write';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    }
  },
  "required": [
    "cwd"
  ]
}', prompt_block = '### git_branch — list local branches

**use when:** seeing what branches exist locally, and which one is current.

**args (model fills):**
- `cwd` (string, required) — repository working directory.

**example:** list local branches

  <tool:git_branch>{"cwd":"~/dos-arch"}</tool>' WHERE name = 'git_branch';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    },
    "branch": {
      "type": "string",
      "description": "branch name"
    },
    "create": {
      "type": "boolean",
      "description": "create the branch before switching"
    }
  },
  "required": [
    "cwd",
    "branch"
  ]
}', prompt_block = '### git_checkout — switch to a branch (optionally create it)

**use when:** moving HEAD to another branch, or starting a new branch off the current one (`create: true`). Verify a clean working tree first; the checkout will refuse to clobber unstaged changes.

**args (model fills):**
- `cwd` (string, required) — repository working directory.
- `branch` (string, required) — branch name.
- `create` (boolean, optional) — create the branch first. Default false.

**example:** start a new feature branch

  <tool:git_checkout>{"cwd":"~/dos-arch","branch":"feat/tool-prompt-blocks","create":true}</tool>' WHERE name = 'git_checkout';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    },
    "message": {
      "type": "string",
      "description": "commit message"
    },
    "stage_all": {
      "type": "boolean",
      "description": "stage every change before committing"
    }
  },
  "required": [
    "cwd",
    "message"
  ]
}', prompt_block = '### git_commit — commit staged changes

**use when:** recording staged changes. With `stage_all: true`, every modified tracked file is staged first (does not pick up untracked files). Skip the call entirely if there is nothing to commit.

**args (model fills):**
- `cwd` (string, required) — repository working directory.
- `message` (string, required) — commit message. One headline line, blank line, then body if needed.
- `stage_all` (boolean, optional) — `git add -u` before committing. Default false.

**example:** commit a focused change

  <tool:git_commit>{"cwd":"~/dos-arch","message":"feat(tools): per-tool prompt_block\n\nEach tool now carries its own TOOLS-section block."}</tool>' WHERE name = 'git_commit';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    },
    "staged": {
      "type": "boolean",
      "description": "show the staged diff instead of the working tree"
    },
    "path": {
      "type": "string",
      "description": "limit the diff to this path"
    }
  },
  "required": [
    "cwd"
  ]
}', prompt_block = '### git_diff — show repo diff

**use when:** inspecting unstaged or staged changes before committing. `staged: true` mirrors `git diff --cached`.

**args (model fills):**
- `cwd` (string, required) — repository working directory.
- `staged` (boolean, optional) — show the staged diff instead of the working tree. Default false.
- `path` (string, optional) — limit the diff to this path.

**example:** see staged changes scoped to one file

  <tool:git_diff>{"cwd":"~/dos-arch","staged":true,"path":"shell_core/shell_render.py"}</tool>' WHERE name = 'git_diff';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    },
    "n": {
      "type": "integer",
      "description": "number of commits, defaults to 10"
    },
    "path": {
      "type": "string",
      "description": "limit the log to this path"
    }
  },
  "required": [
    "cwd"
  ]
}', prompt_block = '### git_log — show recent commits

**use when:** scanning the recent commit history of a repo, optionally scoped to a path.

**args (model fills):**
- `cwd` (string, required) — repository working directory.
- `n` (integer, optional) — number of commits. Defaults to 10.
- `path` (string, optional) — limit the log to this path.

**example:** last 5 commits touching a file

  <tool:git_log>{"cwd":"~/dos-arch","n":5,"path":"shell_core/shell_render.py"}</tool>' WHERE name = 'git_log';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    },
    "rebase": {
      "type": "boolean",
      "description": "rebase instead of fast-forward"
    }
  },
  "required": [
    "cwd"
  ]
}', prompt_block = '### git_pull — pull from upstream

**use when:** syncing the current branch with its upstream. Fast-forward only by default; set `rebase: true` to rebase local commits on top of upstream instead.

**args (model fills):**
- `cwd` (string, required) — repository working directory.
- `rebase` (boolean, optional) — rebase instead of fast-forward. Default false.

**example:** pull main forward

  <tool:git_pull>{"cwd":"~/dos-arch"}</tool>' WHERE name = 'git_pull';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    },
    "force": {
      "type": "boolean",
      "description": "force-with-lease the push"
    }
  },
  "required": [
    "cwd"
  ]
}', prompt_block = '### git_push — push to upstream

**use when:** publishing local commits. Force is `--force-with-lease` only; **confirm with the operator before any force push**, and never force-push `main`/`master`.

**args (model fills):**
- `cwd` (string, required) — repository working directory.
- `force` (boolean, optional) — `--force-with-lease`. Default false.

**example:** push a feature branch

  <tool:git_push>{"cwd":"~/dos-arch"}</tool>' WHERE name = 'git_push';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "cwd": {
      "type": "string",
      "description": "repository working directory"
    }
  },
  "required": [
    "cwd"
  ]
}', prompt_block = '### git_status — show working-tree status

**use when:** checking what is modified, staged, or untracked in a repo before staging or committing.

**args (model fills):**
- `cwd` (string, required) — repository working directory.

**example:** check the dos-arch checkout

  <tool:git_status>{"cwd":"~/dos-arch"}</tool>' WHERE name = 'git_status';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "url": {
      "type": "string",
      "description": "absolute URL"
    },
    "headers": {
      "type": "object",
      "description": "optional request headers"
    }
  },
  "required": [
    "url"
  ]
}', prompt_block = '### http_get — outbound HTTP GET

**use when:** fetching from an external HTTP service. **Not for the substrate API** — that is what `api_get` and the named substrate tools are for. Returns status, headers, body.

**args (model fills):**
- `url` (string, required) — absolute URL.
- `headers` (object, optional) — request headers. Never embed secret values here — reference variable names only if the dispatcher supports interpolation.

**example:** GET an external JSON endpoint

  <tool:http_get>{"url":"https://api.example.com/v1/status","headers":{"Accept":"application/json"}}</tool>' WHERE name = 'http_get';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "url": {
      "type": "string",
      "description": "absolute URL"
    },
    "body": {
      "type": "string",
      "description": "optional raw request body"
    },
    "json": {
      "type": "object",
      "description": "optional JSON request body"
    },
    "headers": {
      "type": "object",
      "description": "optional request headers"
    }
  },
  "required": [
    "url"
  ]
}', prompt_block = '### http_post — outbound HTTP POST

**use when:** posting to an external HTTP service. **Not for the substrate API** — `api_post` and the named substrate tools handle that. Send either `json` (object) or `body` (raw string), not both.

**args (model fills):**
- `url` (string, required) — absolute URL.
- `json` (object, optional) — JSON request body (sets Content-Type automatically).
- `body` (string, optional) — raw request body. Use when the endpoint expects non-JSON.
- `headers` (object, optional) — request headers. Never embed secret values.

**example:** POST JSON to an external service

  <tool:http_post>{"url":"https://api.example.com/v1/events","json":{"type":"ping"}}</tool>' WHERE name = 'http_post';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "pid": {
      "type": "integer",
      "description": "process id to check"
    }
  },
  "required": [
    "pid"
  ]
}', prompt_block = '### proc_check — check if a pid is alive

**use when:** verifying that a process you started (typically via `exec_bg`) is still running.

**args (model fills):**
- `pid` (integer, required) — process id to check.

**example:** check on a backgrounded process

  <tool:proc_check>{"pid":12345}</tool>' WHERE name = 'proc_check';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "pid": {
      "type": "integer",
      "description": "process id to signal"
    },
    "signal": {
      "type": "string",
      "description": "signal name, defaults to SIGTERM"
    }
  },
  "required": [
    "pid"
  ]
}', prompt_block = '### proc_kill — signal a process

**use when:** stopping a process you control. **Destructive — confirm with the operator before killing anything you did not yourself start.** Default signal is SIGTERM; SIGKILL only when SIGTERM has been ignored.

**args (model fills):**
- `pid` (integer, required) — process id to signal.
- `signal` (string, optional) — signal name, e.g. `SIGTERM`, `SIGINT`, `SIGKILL`. Defaults to `SIGTERM`.

**example:** ask a backgrounded process to stop cleanly

  <tool:proc_kill>{"pid":12345}</tool>' WHERE name = 'proc_kill';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "name_filter": {
      "type": "string",
      "description": "optional substring to match against process names"
    }
  },
  "required": []
}', prompt_block = '### proc_list — list running processes

**use when:** checking what is running on the host, optionally filtered by name substring.

**args (model fills):**
- `name_filter` (string, optional) — case-sensitive substring matched against process names. Omit for everything.

**example:** find any python process

  <tool:proc_list>{"name_filter":"python"}</tool>' WHERE name = 'proc_list';

UPDATE tools SET spec = '{
  "type": "object",
  "properties": {
    "url": {
      "type": "string",
      "description": "absolute URL"
    }
  },
  "required": [
    "url"
  ]
}', prompt_block = '### url_fetch — fetch a URL as plain text

**use when:** pulling readable text from a web page or doc URL. Simpler than `http_get` — no headers, no status, just text body.

**args (model fills):**
- `url` (string, required) — absolute URL.

**example:** read a doc

  <tool:url_fetch>{"url":"https://example.com/docs/intro.md"}</tool>' WHERE name = 'url_fetch';
