-- 038 — reseed 1 skills
--   create_flag
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/skills/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Updates content; frontmatter columns
-- are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE skills SET content = '
# create_flag

Open a new flag for this shell. Run on demand with `--new-flag`.

The work is the `create_flag` tool — see its block in the `## TOOLS ##`
section of your boot prompt for the argument shape and a worked example.
The dispatcher''s Bearer token resolves the owner shell on the API side,
so you fill only the content fields.

## Steps

1. **Read the request.** Everything after `--new-flag` is the operator''s
   brief. Extract a short title and a longer description.
2. **Compose the call.** A short, distinctive `display_name`
   (e.g. `CC-099 docs sweep`) plus a `description` that captures
   *what* the flag tracks, *why* it matters, and *what unblocks when it
   closes*. Don''t invent `priority` / `start_date` / `parent_flag_id` /
   `estimated_days` — omit unless the operator named them.
3. **Confirm before opening.** Flags are a CONFIRM surface (memory
   protocol) — get the operator''s explicit yes, then call `create_flag`.
4. **Report the result.** Echo the returned `flag_id` + `display_name`
   back in one line: `Opened CC-099 (flag_id=42).`

## When NOT to use this

- *Resolving* or *updating* an existing flag — different write, no named
  tool yet. Surface the gap rather than opening a duplicate.
- *Listing* what is open — use `--flags` (surface_flags).
' WHERE name = 'create_flag';
