-- 040 — reseed 2 skills
--   decision, surface_flags
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/skills/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Updates content; frontmatter columns
-- are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE skills SET content = '
# decision

- **Trigger:** `--decision`
- **Args:** `[decision] [context]` — interviewed if not provided inline

Record a major decision with context: a decision record (canonical) plus
a line on the active session narrative.

The work is two named tools — see their blocks in the `## TOOLS ##`
section of your boot prompt:

- `create_decision` writes the canonical row to `shell_decisions`.
- `append_narrative` adds the decision line to the active session
  narrative.

Both resolve `shell_id` (and `archive_id`, for narrative) server-side
from the Bearer token, so you fill only the content.

## Scope

Applies to **Major decisions** (M priority), including project-
architectural decisions made while working in a code repo. Repo-facing
ADR files (`DECISIONS.md`, `docs/decisions/`) are mirrors for the repo''s
audience — they do **not** substitute for the decision record. The API
record is canonical; repo files link to it, never the reverse.

## Steps

1. **Resolve args.** If `decision` or `context` were not provided
   inline, interview — "What is the decision?", "What is the context —
   why does this matter?" Wait for each answer. Never guess.
2. **Record the decision** — call `create_decision` with
   `{"decision": "...", "rationale": "..."}`. On error, surface and stop.
3. **Append to the narrative** — call `append_narrative` with
   `{"narrative_entry": "[HH:MM] DECISION: {decision} — {context}"}`.
   A 409 here means the shell has no active archive — surface that gap
   to the operator and stop; the decision row from step 2 stays
   canonical regardless.
4. **Confirm:** "Decision recorded."

## Idempotent?

No. Each invocation records a new decision. Verify before triggering.
' WHERE name = 'decision';

UPDATE skills SET content = '# surface_flags

Surface this shell''s open flags. Run on demand with `--flags`.

The fetch is the `list_flags` tool — see its block in the `## TOOLS ##`
section of your boot prompt. shell_id is resolved server-side from the
Bearer token, so the call is `<tool:list_flags>{}</tool>`.

`resolved` is tri-state: `0` = Open, `1` = Resolved, `2` = Tracking.
Unresolved work is **`0` and `2`** — Open flags are active blockers;
Tracking flags are real but not yet effective (future-scheduled). Resolved
(`1`) flags are done and not surfaced.

## Steps

1. **Fetch** — call `list_flags`. The endpoint scopes server-side to this
   shell; the response carries each row''s schedule fields.
2. **Filter** — keep only rows where `resolved` is `0` or `2`. Drop the
   rest.
3. **Sort** the kept rows: `resolved` ascending (Open `0` before Tracking
   `2`), then priority High → Medium → Low, then `effective_start`
   ascending (nulls last), then `flag_id`.

## Output — two groups, Open first

**Open Flags** (`resolved == 0`) — active blockers. Columns: ID | Priority | Status | Description | Effective Start | Effective End | Parent

**Tracking** (`resolved == 2`) — real but not yet effective; list below the Open group, same columns.

- Status is `schedule_status` (`scheduled` / `in_progress` / `unscheduled`).
- Effective Start/End come from the flag-schedule view (`parent_flag_id`
  chain + `start_date` override + `estimated_days`).
- If both groups empty: state "No open or tracking flags."
' WHERE name = 'surface_flags';
