-- 042 — reseed 1 skills
--   catalogue_sync
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/skills/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Only `content` is updated; frontmatter
-- columns are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE skills SET content = '# catalogue_sync

The catalogue (`dr_*` tables → `v_dr_catalogue`) is a live index of the
substrate''s components — routes, routers, deps, libs, services, repos,
files, automations, env vars. Source of truth is always the underlying
state (code/config); the catalogue is a projection of it.

*Reading* the catalogue is the `surface_catalogue` skill (`GET /catalogue`).
This skill is *maintaining* it — admin work, with the repo at `/substrate`.

## Populator

`/substrate/shell_core/scripts/dr_sync.py` populates all 9 surfaces via
`sync_all`. It runs in two places, and the split matters:

- **host-side — the complete sync.** `./install/api-up.sh` (step [4/6],
  every recompose), `make db-sync`, and a daily cron (see *Run log +
  monitoring*). `dr_repo` needs `git` + the repo''s `.git`; `dr_services`
  needs `node` + `ecosystem.config.cjs` — both only populate here, where
  the host has the tooling and the whole repo.
- **in-container, on every API startup — best-effort refresh.** The
  `dos-api` image is `python:3.12-slim` with no `git`/`node` and mounts
  only `shell_core`, so the repo + services surfaces silently no-op
  there (idempotent — they never clobber the host-synced rows).
  `dr_router`/`dr_api`/`dr_dependencies` refresh fine in-container.
- **`python3 dr_sync.py <target>`** — one surface, for debugging.

## The 11 surfaces

Eight auto-derive from real state; three are curated lists inside `dr_sync.py`:

| Auto-derived | Source |
|---|---|
| `dr_router`, `dr_api` | FastAPI routes + router-module docstrings |
| `dr_dependencies` | declared manifests (`shell_core/requirements.txt`, `shell_core/broker/requirements.txt`, `ui/package.json`); versions enriched from `importlib.metadata` |
| `dr_lib` | backend module docstrings; UI lib first `//` comment in `.js` **or** `.svelte` `<script>` block (recursive under `ui/src/lib/`) |
| `dr_page` | `ui/src/routes/**/+page.svelte`; first `//` in `<script>`, else first `<!-- -->` HTML comment, else `"SvelteKit page: <route>"` |
| `dr_services` | `ecosystem.config.cjs` `summary` fields |
| `dr_repo` | `git remote` + `gh repo view` |
| `dr_db` | `sqlite_master` walk + curated `_DB_PURPOSE_ENTRIES` map for the one-line purpose per table |

| Curated in `dr_sync.py` | List |
|---|---|
| `dr_filepath` | `_FILEPATH_ENTRIES` |
| `dr_automations` | `_AUTOMATION_ENTRIES` |
| `dr_env` | `_ENV_ENTRIES` |

`dr_db` and `dr_page` surface in `v_dr_catalogue` (substrate-wide) but not
`v_shell_catalogue` (DB tables and UI pages are global, not per-shell), so
`shell_dr_link` doesn''t allow them as `ref_table` values.

## When you change something catalogued

| Changed | Keep in sync |
|---|---|
| a route / router | the `summary=` and the router-module docstring |
| a **core** memory endpoint (shell state, flags, seed/L&S, decisions) | also the `MEMORY_PROTOCOL` block in `shell_core/templates/catalog_universal.md`, in the same PR |
| `ecosystem.config.cjs` | the app''s `summary` field |
| a backend / UI lib | the module docstring / first `//` comment |
| a SvelteKit page (`+page.svelte`) | first `//` in `<script>` or top-of-file `<!-- -->` HTML comment |
| a substrate table (DB migration) | add/update its row in `_DB_PURPOSE_ENTRIES` in `dr_sync.py` |
| a notable file, automation, or env var | the matching `_*_ENTRIES` list in `/substrate/shell_core/scripts/dr_sync.py` |

It re-syncs at the next recompose (`./install/api-up.sh`), or run
`make db-sync` host-side. Never hand-write a `dr_*` row — the next sync
overwrites it from source.

The core memory-endpoint map in the boot system prompt is **hand-maintained
prose**, not auto-synced from `dr_api` — it carries when/why semantics the
catalogue''s `description_short` can''t. That surface is stable contract, but
still maturing (e.g. the projects write surface is a known gap). Whoever adds
or moves a core endpoint owns the template edit; nothing catches that drift
automatically.

## Retirement semantics — active vs retired rows

Most populators call `_reap()` after they finish scanning their source — any
`status=''active''` row that wasn''t seen this run flips to `status=''retired''`
(history preserved, never `DELETE`). `dr_filepath` does the same against its
curated-entry set; `dr_repo`/`dr_services`/`dr_env` don''t reap (the universe
of repos/services/env vars is narrow and turnover is rare).

`v_dr_catalogue` and `v_shell_catalogue` filter to `status=''active''` — the
default surface answers "where does X live right now," not "what used to be
here." To see retired history, query the underlying `dr_*` table directly:

```sql
SELECT name, path, status FROM dr_filepath WHERE status = ''retired'';
```

## Run log + monitoring

Every `sync_all` invocation writes one row to `dr_sync_runs` — `trigger_kind`
is `cron`, `startup`, or `manual`. Each row carries the per-surface counts as
JSON, `total_insert`/`total_update`, `had_error`, and a 100-char `error`.
Rolling-100 retention via trigger. It''s the audit trail for catalogue drift.

The only *automatic* full sync is a host-side `systemd` user timer —
`dosarch-dr-sync.timer`, `OnCalendar=*-*-* 04:00:00`, `Persistent=true` so
missed windows catch up on next login. The service still sets
`DR_SYNC_TRIGGER=cron`, so the dr_sync_runs `trigger_kind` column stays
labelled `cron` regardless of how the timer woke it. Nothing else refreshes
`dr_repo`/`dr_services` on its own; without the timer they drift stale
between recomposes.

Monitor via `GET /admin/catalogue-sync` (admin-gated): recent runs,
`last_cron`, `recent_errors`, and `stale` — true when no cron-tagged run
landed in the last 26h. A run that never started leaves no row at all, so
`stale` is the timer-didn''t-fire signal. Watching this is the admin shell''s
job.

## Adding a sync target

1. Pick a stable identity column for the typed table.
2. Write `sync_<target>(conn, app=None)` in `dr_sync.py` — an idempotent
   UPSERT keyed on that column; return
   `{"<surface>": {"insert": N, "update": N, "retire": N}}`. Call `_reap()`
   to drive the `retire` count if the source is fully rescanned each run.
3. Register it in the `SYNCS` dict — `sync_all` and `make db-sync` pick it
   up automatically.
' WHERE name = 'catalogue_sync';
