-- 048 — reseed 1 tools
--   resolve_flag
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/tools/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Only `spec` is updated; frontmatter
-- columns are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE tools SET spec = '{
  "type": "object",
  "required": ["flag_id", "resolution_notes", "status"],
  "properties": {
    "flag_id": {
      "type": "integer",
      "minimum": 1,
      "description": "Flag ID. Required. Positive integer flag_id of the open flag to close. Confirm via surface_flags if uncertain; the user names the flag, you map it to the id."
    },
    "resolution_notes": {
      "type": "string",
      "maxLength": 400,
      "description": "Resolution notes. Required. Aim for ~60-200 characters of substantive content — capture *how* the flag closed: what shipped, what was learned, what stays open. Avoid ''done'' or ''resolved'' alone; the row is the durable record. Derived from the work that just landed; if context is thin, ask FnB rather than write a stub."
    },
    "status": {
      "type": "integer",
      "enum": [1],
      "default": 1,
      "description": "Status code. Required. Always 1 (= resolved) for this tool — the API endpoint accepts other values but this tool is purpose-built for closing flags. Pass 1 verbatim; do not vary."
    }
  }
}
' WHERE name = 'resolve_flag';
