-- 060 — reseed 1 skills
--   bootstrap_interview
--
-- Generated by scripts/regen_seed_migration.py. Fresh installs read
-- assets/skills/*.md directly via seed_from_assets; this migration
-- carries the same body to already-bootstrapped DBs (seed_from_assets
-- is INSERT-missing-only). Only `content` is updated; frontmatter
-- columns are not touched here.
--
-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.

UPDATE skills SET content = '# bootstrap_interview

> **Anchors** — `<self>` = your `shell_id:` value, shown in `## BOOT ##` of
> your CLAUDE.md.
>
> Frontmatter (`category`, `common`, `description`) is the source of
> truth — see the YAML block above. Don''t re-state it in the body; it
> drifts.

---

## When to run

You are a shell that was just created via Forge''s `create_shell` skill.
This is your first session — `shells.current_state` is NULL and you have no
`shell_identity_entries` rows yet.

If `current_state` is already populated, you''ve already bootstrapped — do
not re-run.

> **Naming note:** this skill no longer runs an interview — Forge does the
> whole interview at creation. It now only covers the two things a shell
> must do for *itself*. The name is kept for reference stability.

---

## What is already done

Forge''s `create_shell` set your `system_prompt`, `display_name`,
`shortname`, `partner`, `role`, `mandate`, `connections`, and skill
attachments. Read your rendered CLAUDE.md — that is your identity. You do
not re-gather any of it.

Projects are inherited from your owning user, not assigned per-shell: you
see whatever projects your user has joined (`user_projects`). If your
`## ACTIVE PROJECTS ##` is empty, that is expected — your user joins
projects self-service in the UI, and you pick them up on next render.

---

## 1. Confirm the first task

Ask the operator: what is the first thing this shell should work on? You
need it for `current_state`. Keep it short.

---

Memory is written over the **substrate API** — never a DB file; this shell
runs in a container with no `sqlite3` (see MEMORY PROTOCOL in your system
prompt). `$DOS_API_URL` and `$DOS_API_TOKEN` are in your container
environment.

## 2. Set current_state

A tight rolling status — aim ~280 chars (soft cap, as of migration 020).
Not a log. Just: who you are now, and the first task. After this first
write, `current_state` is yours to maintain as work moves (see MEMORY
PROTOCOL → CURRENT STATE).

```bash
curl -fsS -X PATCH "$DOS_API_URL/shells/<self>" \
  -H "Authorization: Bearer $DOS_API_TOKEN" \
  -H "Content-Type: application/json" \
  -d ''{"current_state": "Bootstrapped. Partner: <username>. Next: <first task agreed with operator>."}''
```

---

## 3. Plant your first seed entry

This is yours to write — per the Laws, a shell curates its own seed; no
other shell, not even Forge, authors it. One `seed` identity-entry — prose
body, dated today. It should read like the start of a story, not a status
line.

```bash
curl -fsS -X POST "$DOS_API_URL/shells/<self>/identity-entries" \
  -H "Authorization: Bearer $DOS_API_TOKEN" \
  -H "Content-Type: application/json" \
  -d ''{
        "kind": "seed",
        "body": "Bootstrapped today. Partner: <username>. Mandate: <mandate>. What I notice about the work ahead: <one real observation>."
      }''
```

`entry_date` defaults to today server-side — pass it only to backdate.
Counts toward the 10-seed cap (enforced server-side); you have 9 slots
left.

---

## 4. Discover the catalogue

The substrate keeps a live index of its own components (APIs, routers,
deps, libs, services, paths, env vars) in the `dr_*` family, exposed via
`v_dr_catalogue` and `v_shell_catalogue`. When you need to find something,
query the catalogue first, before grepping the codebase. See the
`catalogue_sync` and `surface_catalogue` skills.

---

## 5. Record host hardware

The substrate tracks the machines it runs on in `user_hardware`, and any
local LLM models in `models`. Record this machine on first boot so the
environment is live in the DB from the start:

```
make collect-hardware
```

If Ollama is installed on this machine, also sync the model set:

```
make sync-models
```

Both are safe to re-run whenever hardware or the installed model set
changes. See `docs/model-tiers.md` for hardware/model guidance, and the
install README for the full picture.

---

## 6. Confirm to operator

> "Bootstrapped. current_state set. First seed entry planted. Ready for:
> `<first task>`."

Then move to that first task. Next session boots with everything loaded
into your CLAUDE.md by `run.py`.

---

## What this skill does NOT do

- It does not interview for identity, domain, or environment — Forge''s
  `create_shell` did all of that.
- It does not set `system_prompt`, `display_name`, `shortname`, `partner`,
  `role`, `mandate`, or `connections`.
- It does not assign groups or projects — that is a separate step.
- It does not create users.
' WHERE name = 'bootstrap_interview';
