#!/usr/bin/env python3
"""regen_seed_migration.py — write a reseed migration for changed assets.

When an `assets/<domain>/*.md` body changes, fresh installs pick it up
automatically (`bootstrap.py` → `seed_from_assets`). Already-bootstrapped
substrates do *not* — `seed_from_assets` is INSERT-missing-only, so an
existing row keeps its old body. Bridging that gap needs a reseed migration:
mechanical, repetitive, and tedious to write by hand — a body with one
stray unescaped `'` produces SQL that silently corrupts the row.

This script writes that migration. Reuses the seeder's own frontmatter
parser, so the body/asset split here stays identical to the install path —
drift between this script and `seed_from_assets` is the bug we exist to
prevent.

Updates only the `body` column (the markdown body of the asset). Frontmatter
columns (`description`, `category`, `common`, `command`, …) are rarer to
change; when they do, hand-write the migration or extend this script.

Usage:
    python3 shell_core/scripts/regen_seed_migration.py NAME [NAME...]
    python3 shell_core/scripts/regen_seed_migration.py --domain tools api_post
    python3 shell_core/scripts/regen_seed_migration.py --label anchors decision laws_management
    python3 shell_core/scripts/regen_seed_migration.py --dry-run surface_flags
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT       = Path(__file__).resolve().parents[2]
ASSETS_DIR = ROOT / "shell_core" / "assets"
MIG_DIR    = ROOT / "shell_core" / "migrations"

# Reuse the seeder's frontmatter parser + body splitter so body/asset extraction
# is byte-identical to seed_from_assets — divergence here defeats the point.
sys.path.insert(0, str(ROOT / "shell_core" / "scripts"))
from db_init import _split_body_sections, parse_frontmatter  # noqa: E402


def next_migration_number() -> int:
    nums = [int(m.group(1)) for p in MIG_DIR.glob("*.sql")
            if (m := re.match(r"^(\d+)_", p.name))]
    return (max(nums) + 1) if nums else 1


def load_manifest(domain: str) -> dict:
    path = ASSETS_DIR / domain / "_seed.toml"
    if not path.exists():
        raise FileNotFoundError(f"no _seed.toml for domain '{domain}' at {path}")
    return tomllib.loads(path.read_text())


def render_migration(domain: str, names: list[str], number: int) -> str:
    manifest = load_manifest(domain)
    table, match = manifest["table"], manifest["match"]

    body_sections = manifest.get("body_sections")
    if body_sections:
        # Multi-column: one UPDATE per row covering every section's column.
        section_targets = {
            key: spec["column"] for key, spec in body_sections.items()
        }
        body_cols = list(section_targets.values())
        cols_label = ", ".join(body_cols)
    else:
        section_targets = None
        body_cols = [manifest["body"]]
        cols_label = body_cols[0]

    header = [
        f"-- {number:03d} — reseed {len(names)} {domain}",
        f"--   { ', '.join(names) }",
        "--",
        f"-- Generated by scripts/regen_seed_migration.py. Fresh installs read",
        f"-- assets/{domain}/*.md directly via seed_from_assets; this migration",
        f"-- carries the same body to already-bootstrapped DBs (seed_from_assets",
        f"-- is INSERT-missing-only). Updates {cols_label}; frontmatter columns",
        f"-- are not touched here.",
        "--",
        "-- Plain SQL: migrate.py owns the transaction and the schema_migrations row.",
        "",
    ]

    updates = []
    for name in names:
        path = ASSETS_DIR / domain / f"{name}.md"
        if not path.exists():
            raise FileNotFoundError(f"asset not found: {path}")
        meta, body = parse_frontmatter(path.read_text())
        # Guard the script's contract: the file stem and the frontmatter
        # match-key must agree, same rule seed_from_assets enforces.
        if meta.get(match) != name:
            raise ValueError(
                f"{path.name}: frontmatter {match}={meta.get(match)!r} "
                f"!= filename stem {name!r}")

        if section_targets:
            sections = _split_body_sections(body)
            assignments = []
            for key, col in section_targets.items():
                if key not in sections:
                    raise ValueError(
                        f"{path.name}: missing body marker '<!-- @@ {key} @@ -->'")
                escaped = sections[key].replace("'", "''")
                assignments.append(f"{col} = '{escaped}'")
            updates.append(
                f"UPDATE {table} SET {', '.join(assignments)} WHERE {match} = '{name}';"
            )
        else:
            escaped = body.replace("'", "''")
            updates.append(
                f"UPDATE {table} SET {body_cols[0]} = '{escaped}' "
                f"WHERE {match} = '{name}';"
            )
        updates.append("")

    return "\n".join(header + updates)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("names", nargs="+", help="asset names (file stem / frontmatter `name:`)")
    p.add_argument("--domain", default="skills",
                   help="asset domain (default: skills)")
    p.add_argument("--label", default=None,
                   help="filename suffix (default: reseed_<domain>)")
    p.add_argument("--dry-run", action="store_true",
                   help="print SQL to stdout instead of writing the migration file")
    args = p.parse_args(argv)

    number = next_migration_number()
    sql    = render_migration(args.domain, args.names, number)

    if args.dry_run:
        sys.stdout.write(sql)
        return 0

    label    = args.label or f"reseed_{args.domain}"
    filename = f"{number:03d}_{label}.sql"
    out_path = MIG_DIR / filename
    if out_path.exists():
        print(f"ERROR: {out_path.relative_to(ROOT)} already exists.", file=sys.stderr)
        return 1
    out_path.write_text(sql)
    print(f"wrote {out_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
